//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaIrt.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class livro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public livro()
        {
            this.reserva = new HashSet<reserva>();
        }
    
        public int liv_id_livro { get; set; }
        public string liv_ds_isbn { get; set; }
        public string liv_ds_nome { get; set; }
        public string liv_ds_autor { get; set; }
        public Nullable<System.DateTime> liv_dt_publicacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reserva> reserva { get; set; }
    }
}
