//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaIrt.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        public int res_id_reserva { get; set; }
        public int res_id_livro { get; set; }
        public string res_ds_usuario { get; set; }
        public System.DateTime res_dt_entrega { get; set; }
    
        public virtual livro livro { get; set; }
    }
}
